# Generated by Django 4.1.3 on 2022-11-13 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('dueño', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=11)),
                ('mail', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Correspondencia',
            fields=[
                ('id_correo', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('conserje', models.CharField(max_length=50)),
                ('remitente', models.CharField(max_length=50)),
                ('destinatario', models.CharField(max_length=50)),
                ('numero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='correos.residencia')),
            ],
        ),
    ]
