# Generated by Django 4.1.3 on 2022-11-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencia',
            name='estado',
            field=models.CharField(choices=[('REC', 'Recibido'), ('ENT', 'Entregado')], default='REC', max_length=9),
        ),
    ]
