# Generated by Django 4.1.3 on 2022-11-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0005_alter_correspondencia_fecha_recepcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencia',
            name='fecha_emtrega',
            field=models.DateField(default=None),
        ),
    ]
