# Generated by Django 4.1.3 on 2022-11-14 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0008_correspondencia_fecha_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correspondencia',
            name='fecha_entrega',
        ),
    ]
