# Generated by Django 4.1.3 on 2022-11-14 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('correos', '0009_remove_correspondencia_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='conserje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
