# Generated by Django 4.1.3 on 2022-11-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0010_alter_correspondencia_conserje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='fecha_recepcion',
            field=models.DateField(),
        ),
    ]
